name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Download Ngrok
      run: curl -o ngrok.zip https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-darwin-amd64.zip

    - name: Extract Ngrok
      run: unzip ngrok.zip -d ngrok

    - name: Auth Ngrok
      run: ./ngrok/ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable Remote Desktop
      run: |
        sudo systemsetup -setremotelogin on
        sudo /usr/bin/defaults write /Library/Preferences/com.apple.RemoteManagement.plist EnableScreenSharing -int 1
        sudo /usr/bin/defaults write /Library/Preferences/com.apple.RemoteManagement.plist EnableARD -int 1

    - name: Create User if not exists
      run: |
        if ! id "runneradmin" &>/dev/null; then
          sudo dscl . -create /Users/runneradmin
          sudo dscl . -create /Users/runneradmin UserShell /bin/bash
          sudo dscl . -create /Users/runneradmin RealName "Runner Admin"
          sudo dscl . -create /Users/runneradmin UniqueID "1001"
          sudo dscl . -create /Users/runneradmin PrimaryGroupID 1000
          sudo dscl . -create /Users/runneradmin NFSHomeDirectory /Users/runneradmin
          sudo dscl . -passwd /Users/runneradmin P@ssw0rd!
          sudo dscl . -append /Groups/admin GroupMembership runneradmin
        fi

    - name: Create Tunnel
      run: ./ngrok/ngrok tcp 5900
